spring.application.name=datagg

spring.profiles.include=secret

spring.datasource.url=jdbc:h2:mem:datagg
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

riot.api.account-base-url=https://asia.api.riotgames.com
riot.api.kr-base-url=https://kr.api.riotgames.com